javac ./com/notebook/GlobalVariables.java
javac ./com/notebook/FileStringProcess.java
javac ./com/notebook/SymbolProcess.java
javac ./com/notebook/TextProcess.java
javac ./com/notebook/CreateStyles.java
javac ./com/notebook/MenuEdit.java
javac ./com/notebook/MessageProcess.java
javac ./com/notebook/ButtonProcess.java
javac ./com/notebook/SearchProcess.java
javac NoteBook.java
java NoteBook